### ISSUE TITLE
complie ERROR example/esp-idf

### ISSUE THREAD

**Issue by chaabanihoussem** [Xinyuan-LilyGO/T-Dongle-S3#15]
Hi,

I'm trying to build the example "ESP-IDF" given in the repo
I downloaded the repo with the sub-modules, and target set esp32s3, and still build failed :

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
esp-idf/LovyanGFX/CMakeFiles/__idf_LovyanGFX.dir/src/lgfx/v1/misc/pixelcopy.cpp.obj -c /home/hch/esp/esp-idf/examples/T-Dongle-S3/example/ESP-IDF/components/LovyanGFX/src/lgfx/v1/misc/pixelcopy.cpp
/home/hch/esp/esp-idf/examples/T-Dongle-S3/example/ESP-IDF/components/LovyanGFX/src/lgfx/v1/misc/pixelcopy.cpp: In constructor 'lgfx::v1::pixelcopy_t::pixelcopy_t(const void*, lgfx::v1::color_depth_t, lgfx::v1::color_depth_t, bool, const void*, uint32_t)':
/home/hch/esp/esp-idf/examples/T-Dongle-S3/example/ESP-IDF/components/LovyanGFX/src/lgfx/v1/misc/pixelcopy.cpp:39:25: error: member 'lgfx::v1::pixelcopy_t::<anonymous>' is used uninitialized [-Werror=uninitialized]
   39 |     , src_mask  ( (1 << src_bits) - 1 )
      |                         ^~~~~~~~
/home/hch/esp/esp-idf/examples/T-Dongle-S3/example/ESP-IDF/components/LovyanGFX/src/lgfx/v1/misc/pixelcopy.cpp:40:25: error: member 'lgfx::v1::pixelcopy_t::<anonymous>' is used uninitialized [-Werror=uninitialized]
   40 |     , dst_mask  ( (1 << dst_bits) - 1 )
      |                         ^~~~~~~~
cc1plus: some warnings being treated as errors
[608/654] Building CXX object esp-idf/LovyanGFX/CMakeFiles/__idf_LovyanGFX.dir/src/lgfx/v1/LGFXBase.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/hch/esp/esp-idf/examples/T-Dongle-S3/example/ESP-IDF/build/log/idf_py_stderr_output_59037 and /home/hch/esp/esp-idf/examples/T-Dongle-S3/example/ESP-IDF/build/log/idf_py_stdout_output_59037

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

waiting for your help
Thanks

**Comment by chaabanihoussem** [comment]
managed to build on esp idf 4.0
